# Generated by Django 4.2.7 on 2024-05-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_city_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='created',
            new_name='created_at',
        ),
    ]
